[package]
name = "sensor-node"
version = "0.1.0"
authors = ["James Munns <james.munns@ferrous-systems.com>"]
edition = "2018"

[dependencies]
panic-halt = "0.2.0"
nb = "0.1.1"
cortex-m-rt = "0.6.3"

[dependencies.dwm1001]
version = "0.1.0"
features = [ "dev", "rt" ]
