language: rust

rust:
  - stable
  - beta
  - nightly

install:
  - rustup target add thumbv7em-none-eabihf

script:
- cargo build --all
- cargo test --manifest-path=./uhr/Cargo.toml --target x86_64-unknown-linux-gnu
