[workspace]

members = [
    "sensor-node",
    "uarte-logger",

    "utils",
    "protocol",
]


[patch.crates-io.dwm1001]
git = "https://github.com/braun-robotics/rust-dwm1001"
rev = "construct-by-parts"
